INSERT INTO `BAAKO`.`PLAINUSER` (`USERNAME`, `BIRTHDATE`, `EMAIL`, `PASSWORD`) VALUES ('ruben', '1995-01-19', 'rubensancor@gmail.com', 'asd');
INSERT INTO `BAAKO`.`PLAINUSER` (`USERNAME`, `BIRTHDATE`, `EMAIL`, `PASSWORD`) VALUES ('gaizka', '1995-10-03', 'gvirum@gmail.com', 'asd');

INSERT INTO `BAAKO`.`DESIGNER` (`NAME`) VALUES ('Elated Games');
INSERT INTO `BAAKO`.`DESIGNER` (`NAME`) VALUES ('Ubisoft');

INSERT INTO `BAAKO`.`CATEGORY` (`NAME`) VALUES ('MMORPG');
INSERT INTO `BAAKO`.`CATEGORY` (`NAME`) VALUES ('Shooter');
INSERT INTO `BAAKO`.`CATEGORY` (`NAME`) VALUES ('Sports');