INSERT INTO `BAAKO`.`PLAINUSER` (`USERNAME`, `BIRTHDATE`, `EMAIL`, `PASSWORD`) VALUES ('ruben', '1995-01-19', 'rubensancor@gmail.com', 'asd');
INSERT INTO `BAAKO`.`PLAINUSER` (`USERNAME`, `BIRTHDATE`, `EMAIL`, `PASSWORD`) VALUES ('gaizka', '1995-10-03', 'gvirum@gmail.com', 'asd');
INSERT INTO `BAAKO`.`PLAINUSER` (`USERNAME`, `BIRTHDATE`, `EMAIL`, `PASSWORD`) VALUES ('Carlos', '1995-12-04', 'carlos@gmail.com', 'asd');
INSERT INTO `BAAKO`.`PLAINUSER` (`USERNAME`, `BIRTHDATE`, `EMAIL`, `PASSWORD`) VALUES ('Adrian', '1994-07-23', 'adrian@gmail.com', 'asd');

INSERT INTO `BAAKO`.`DESIGNER` (`NAME`) VALUES ('Elated Games');
INSERT INTO `BAAKO`.`DESIGNER` (`NAME`) VALUES ('Ubisoft');
INSERT INTO `BAAKO`.`DESIGNER` (`NAME`) VALUES ('Rockestars');
INSERT INTO `BAAKO`.`DESIGNER` (`NAME`) VALUES ('Nvidia');
INSERT INTO `BAAKO`.`DESIGNER` (`NAME`) VALUES ('Bugisoft');



INSERT INTO `BAAKO`.`CATEGORY` (`NAME`) VALUES ('MMORPG');
INSERT INTO `BAAKO`.`CATEGORY` (`NAME`) VALUES ('Shooter');
INSERT INTO `BAAKO`.`CATEGORY` (`NAME`) VALUES ('Sports');
INSERT INTO `BAAKO`.`CATEGORY` (`NAME`) VALUES ('Cars');
INSERT INTO `BAAKO`.`CATEGORY` (`NAME`) VALUES ('Education');
INSERT INTO `BAAKO`.`CATEGORY` (`NAME`) VALUES ('Free World');